name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip openjdk-8-jdk
          pip install --upgrade pip
          pip install buildozer cython

      - name: Cache buildozer
        uses: actions/cache@v2
        with:
          path: | 
            ~/.buildozer
            ~/.local/share/python-for-android
          key: ${{ runner.os }}-buildozer-${{ hashFiles('**/buildozer.spec') }}

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: KivyApp-APK
          path: bin/*.apk
