name: Build Kivy APK

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-setuptools python3-pip
        sudo apt-get install -y build-essential ccache git libncurses5 libffi-dev libssl-dev \
          liblzma-dev zlib1g-dev automake autoconf libtool unzip zip
        sudo apt-get install -y openjdk-8-jdk
        python3 -m pip install --upgrade cython virtualenv

    - name: Install Buildozer
      run: pip3 install buildozer

    - name: Install Cython
      run: pip3 install cython==0.29.21

    - name: Build the APK
      run: |
        buildozer android debug
        mkdir -p ./dist
        cp ./bin/*.apk ./dist/

    - name: Upload APK
      uses: actions/upload-artifact@
